In [64]:
import numpy as np

In [65]:
#list to array
l = [1,2,3,4]

In [66]:
type(l)

list

In [67]:
l_new = np.array(l)

In [68]:
type(l_new)

numpy.ndarray

In [69]:
l_new

array([1, 2, 3, 4])

In [70]:
two_dimension = np.array([[1,2],[3,4]])

In [71]:
two_dimension

array([[1, 2],
       [3, 4]])

In [72]:
type(two_dimension)

numpy.ndarray

In [73]:
# other way to convert
np.asarray(l)

array([1, 2, 3, 4])

# NumPy Array Conversion Functions

NumPy provides several array conversion functions that allow you to convert data into arrays or change the properties of existing arrays. In this guide, we will explore the following functions: `asarray`, `asanarray`, `asanyarray`, `asarray_chkfinite`, `ascontiguousarray`, `asfarray`, and `asfortranarray`.

## 1. `asarray`

The `asarray` function converts input data into an ndarray, which is a multi-dimensional array object provided by NumPy. If the input is already an ndarray, it returns a new reference to the input data. However, if the input is a sequence (list, tuple, etc.), it creates a new ndarray with the same data.

Syntax: `numpy.asarray(a, dtype=None, order=None)`

## 2. `asanarray`

The `asanarray` function is similar to `asarray`, but it always returns a new ndarray. If the input is already an ndarray, it makes a copy of the data. If the input is a sequence, it creates a new ndarray.

Syntax: `numpy.asanarray(a, dtype=None, order=None)`

## 3. `asanyarray`

The `asanyarray` function converts input data into an ndarray, similar to `asarray`. However, if the input is a subclass of ndarray, it returns the input as is without creating a new ndarray. This function is useful when you want to accept various types of inputs without explicitly converting them into ndarrays.

Syntax: `numpy.asanyarray(a, dtype=None, order=None)`

## 4. `asarray_chkfinite`

The `asarray_chkfinite` function converts input data into an ndarray, while also checking if the input contains any NaN or infinity values. If any such values are found, a ValueError is raised. Otherwise, it behaves similarly to `asarray`.

Syntax: `numpy.asarray_chkfinite(a, dtype=None, order=None)`

## 5. `ascontiguousarray`

The `ascontiguousarray` function creates a new ndarray with the same data as the input, but in a contiguous memory layout. If the input is already contiguous, it returns the input itself. Otherwise, it creates a new contiguous ndarray and copies the data.

Syntax: `numpy.ascontiguousarray(a, dtype=None)`

## 6. `asfarray`

The `asfarray` function converts the input data into a floating-point ndarray, regardless of its original data type. It is similar to `asarray`, but always returns a floating-point array.

Syntax: `numpy.asfarray(a, dtype=<class 'numpy.float64'>)`

## 7. `asfortranarray`

The `asfortranarray` function creates a new ndarray with the same data as the input, but in Fortran (column-major) order. If the input is already in Fortran order, it returns the input itself. Otherwise, it creates a new ndarray and copies the data in Fortran order.

Syntax: `numpy.asfortranarray(a, dtype=None)`

---

These conversion functions provide various ways to convert or modify arrays according to your needs. Remember to consult the NumPy documentation for more detailed information and examples.


In [74]:
li = [1,2,3,4]

In [75]:
li_as_array = np.asarray(li)

In [76]:
li_as_matrix = np.asmatrix(li)

In [77]:
li_as_matrix

matrix([[1, 2, 3, 4]])

In [78]:
li_as_array_p2 = np.asarray(li_as_matrix)

In [79]:
li_as_array_p2

array([[1, 2, 3, 4]])

```
# NumPy Array Conversion Functions

NumPy provides several array conversion functions that allow you to convert data into arrays or change the properties of existing arrays. In this guide, we will explore the functions `asarray`, `asanarray`, `asanyarray`, `asarray_chkfinite`, `ascontiguousarray`, `asfarray`, and `asfortranarray`.

## Conversion Behavior

When converting data using the NumPy array conversion functions, it's important to understand the differences in behavior. Let's consider the following initial list:

```python
l = [1, 2, 3, 4]
```

1. Using `numpy.asarray(l)`: This successfully converts the list `l` into a NumPy array.

2. Using `numpy.asmatrix(l)`: This converts the list `l` into a matrix, which is a subclass of the ndarray object. The resulting object is a matrix, not a regular array.

3. Using `numpy.asarray(numpy.asmatrix(l))`: This successfully converts the matrix obtained from `numpy.asmatrix(l)` back into a NumPy array. The `numpy.asarray` function treats the matrix object as an ndarray and returns a new array.

## Conversion Failure: `asanarray`

The `asanarray` function behaves similarly to `asarray`, but with one key difference. If the input is already an ndarray, `asanyarray` returns a new reference to the input data, whereas `asanarray` always creates a new ndarray. However, if the input is a matrix, `asanyarray` returns the input as is, while `asanarray` converts it into a regular array. This can lead to conversion failures.

For example, if we use `numpy.asanarray(numpy.asmatrix(l))`, it will fail to convert the matrix back into an array. The resulting object will still be a matrix, not an array.

## Conversion Success and Failure Summary

Here is a summary of possible conversion outcomes for different combinations:

- `numpy.asarray(l)`: Successful conversion of the list `l` to an array.
- `numpy.asmatrix(l)`: Successful conversion of the list `l` to a matrix.
- `numpy.asarray(numpy.asmatrix(l))`: Successful conversion of the matrix back to an array.
- `numpy.asanyarray(l)`: Successful conversion of the list `l` to an array.
- `numpy.asanyarray(numpy.asmatrix(l))`: Conversion failure. The resulting object will still be a matrix, not an array.
- `numpy.asarray_chkfinite(l)`: Successful conversion of the list `l` to an array.
- `numpy.asarray_chkfinite(numpy.asmatrix(l))`: Successful conversion of the matrix back to an array.
- `numpy.ascontiguousarray(l)`: Successful conversion of the list `l` to an array.
- `numpy.ascontiguousarray(numpy.asmatrix(l))`: Successful conversion of the matrix back to an array.
- `numpy.asfarray(l)`: Successful conversion of the list `l` to a floating-point array.
- `numpy.asfarray(numpy.asmatrix(l))`: Successful conversion of the matrix back to a floating-point array.
- `numpy.asfortranarray(l)`: Successful conversion of the list `l` to an array.
- `numpy.asfortranarray(numpy.asmatrix(l))`: Successful conversion of the matrix back to an array.
```

In [80]:
l = [1,2,3,4]

In [81]:
a = np.asarray(l)

In [82]:
a

array([1, 2, 3, 4])

In [83]:
c = a

In [84]:
c[0]

1

In [85]:
c[0] = 1000

In [86]:
c

array([1000,    2,    3,    4])

In [87]:
a

array([1000,    2,    3,    4])

In [88]:
d = np.copy(a)

In [89]:
d[0]

1000

In [90]:
d[0] = 467

In [91]:
d

array([467,   2,   3,   4])

In [92]:
a

array([1000,    2,    3,    4])

## Shallow Copy and Deep Copy in Python

In Python, when dealing with objects, including lists, dictionaries, and user-defined classes, it's important to understand the concepts of shallow copy and deep copy. These concepts determine how data is copied and stored in memory. Let's explore each of them in detail.

### Shallow Copy

A shallow copy creates a new object that references the original elements. It copies the reference of the original object rather than duplicating the underlying data. Any changes made to the original elements or the copied elements will be reflected in both objects.

#### Syntax

In Python, you can create a shallow copy using various methods:

1. Using the `copy()` method:
   ```python
   new_list = original_list.copy()
   ```

2. Using the `list()` constructor:
   ```python
   new_list = list(original_list)
   ```

3. Using slicing:
   ```python
   new_list = original_list[:]
   ```

#### Example

Let's consider a simple example using a list:

```python
original_list = [1, 2, [3, 4]]
shallow_copy = original_list.copy()

# Modify the original list
original_list[0] = 10

# Modify the nested list
original_list[2][0] = 30

print(original_list)    # Output: [10, 2, [30, 4]]
print(shallow_copy)     # Output: [1, 2, [30, 4]]
```

In this example, `shallow_copy` is created using a shallow copy of `original_list`. When we modify the elements of `original_list`, both `original_list` and `shallow_copy` are affected. However, if we modify the nested list, it is reflected in both objects since they share the same reference to the nested list.

#### Use Cases and Analogies

Shallow copy is useful when you want to create a new object that shares some or all of its data with the original object. It can be beneficial in scenarios where memory efficiency is a concern and you don't need a completely independent copy of the object.

An analogy to understand shallow copy is like having multiple keys to the same door. Imagine you have a room with furniture. The original key (object) grants access to the room. A shallow copy is like having another key that opens the same door. Both keys provide access to the same room and any changes made to the furniture will be visible with either key.

In real-life examples, consider a classroom where students have access to shared study materials. If a student modifies the materials, those changes are visible to other students who have access to the same resources.

### Deep Copy

A deep copy creates a new object with completely independent data. It duplicates the underlying data and any changes made to the original or copied objects do not affect each other.

#### Syntax

In Python, you can create a deep copy using the `deepcopy()` function from the `copy` module:

```python
import copy

new_list = copy.deepcopy(original_list)
```

#### Example

Let's extend the previous example to demonstrate deep copy:

```python
import copy

original_list = [1, 2, [3, 4]]
deep_copy = copy.deepcopy(original_list)

# Modify the original list
original_list[0] = 10

# Modify the nested list
original_list[2][0] = 30

print(original_list)    # Output: [10, 2, [30, 4]]
print(deep_copy)        # Output: [1, 2, [3, 4]]
```

In this example, `deep_copy` is created using a deep copy of `original_list`. When we modify the elements of `original_list`, the `deep_copy` remains unaffected. Changes made to the nested list are independent between the two objects.

### Use Cases and Analogies

Deep copy is useful when you need to create a completely independent copy of an object. It ensures that any changes made to the original or copied object do not affect each other. Deep copy is typically used when you want to modify one copy without impacting the other.

An analogy for deep copy is like having different keys to different doors that lead to identical rooms. Each key provides access to a separate room, and changes made to one room are not visible in the other.

In real-life examples, consider a library where students can borrow books. If a student borrows a book and makes annotations or highlights, those changes are not visible to other students who borrow the same book later.

## Choosing Between Shallow Copy and Deep Copy

The choice between shallow copy and deep copy depends on the specific requirements of your program. Consider the following factors:

- If you need a new object that shares data with the original object, use shallow copy.
- If you need a completely independent copy with no shared data, use deep copy.
- If your object does not contain nested mutable objects (e.g., lists within lists), shallow copy may be sufficient.
- If your object contains nested mutable objects and you want to avoid unintended side effects, use deep copy.

It's important to select the appropriate copy method based on your specific needs to ensure the desired behavior.

---

That covers the concepts of shallow copy and deep copy in Python. Understanding these concepts will help you make informed decisions when working with objects and ensure you create the copies that best suit your requirements.

In [93]:
np.fromfunction(lambda x,y : x == y , (3,3) )

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [94]:
np.fromfunction(lambda x,y : x * y , (3,3) )

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [95]:
np.fromfunction(lambda x,y : x + y , (3,3) )

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [96]:
iterable = (i * i for i in range(6))

In [97]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16., 25.])

In [98]:
np.fromiter(iterable,int)

array([], dtype=int64)

In [99]:
np.fromstring('12 45 67', sep=' ')

array([12., 45., 67.])

In [100]:
l = [1,2,3,4,5,6,7]

In [101]:
a = np.asarray(l)

In [102]:
a.ndim

1

In [103]:
l = [[1,2],[3,4]]

In [104]:
a = np.asarray(l)

In [105]:
a.ndim

2

In [106]:
a.size

4

In [107]:
a.shape

(2, 2)

In [108]:
a.dtype

dtype('int64')

In [109]:
arr3 = np.array([(1.34,78,97), (76.4,98,00)])

In [110]:
arr3

array([[ 1.34, 78.  , 97.  ],
       [76.4 , 98.  ,  0.  ]])

In [111]:
arr3.dtype

dtype('float64')

In [112]:
list(range(5))

[0, 1, 2, 3, 4]

In [113]:
list(range(0.1,5))

TypeError: 'float' object cannot be interpreted as an integer

In [114]:
np.arange(2.98,7.87)

array([2.98, 3.98, 4.98, 5.98, 6.98])

In [115]:
np.arange(2.3,8.7,0.45)

array([2.3 , 2.75, 3.2 , 3.65, 4.1 , 4.55, 5.  , 5.45, 5.9 , 6.35, 6.8 ,
       7.25, 7.7 , 8.15, 8.6 ])

In [116]:
list(np.arange(2.3,8.7,0.45))

[2.3,
 2.75,
 3.2,
 3.6500000000000004,
 4.1000000000000005,
 4.550000000000001,
 5.000000000000001,
 5.450000000000001,
 5.900000000000001,
 6.350000000000001,
 6.800000000000002,
 7.250000000000002,
 7.700000000000002,
 8.150000000000002,
 8.600000000000001]

In [117]:
np.linspace(1,10,200)

array([ 1.        ,  1.04522613,  1.09045226,  1.13567839,  1.18090452,
        1.22613065,  1.27135678,  1.31658291,  1.36180905,  1.40703518,
        1.45226131,  1.49748744,  1.54271357,  1.5879397 ,  1.63316583,
        1.67839196,  1.72361809,  1.76884422,  1.81407035,  1.85929648,
        1.90452261,  1.94974874,  1.99497487,  2.04020101,  2.08542714,
        2.13065327,  2.1758794 ,  2.22110553,  2.26633166,  2.31155779,
        2.35678392,  2.40201005,  2.44723618,  2.49246231,  2.53768844,
        2.58291457,  2.6281407 ,  2.67336683,  2.71859296,  2.7638191 ,
        2.80904523,  2.85427136,  2.89949749,  2.94472362,  2.98994975,
        3.03517588,  3.08040201,  3.12562814,  3.17085427,  3.2160804 ,
        3.26130653,  3.30653266,  3.35175879,  3.39698492,  3.44221106,
        3.48743719,  3.53266332,  3.57788945,  3.62311558,  3.66834171,
        3.71356784,  3.75879397,  3.8040201 ,  3.84924623,  3.89447236,
        3.93969849,  3.98492462,  4.03015075,  4.07537688,  4.12

In [118]:
ar4 = np.zeros((3,4,2,3))

In [119]:
ar4

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [120]:
np.ones(1)

array([1.])

In [121]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [122]:
np.ones((4,2,3))

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [123]:
np.ones((6,4,2,3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
       

In [124]:
np.ones((5,6,4,2,3))

array([[[[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]]],


        [[[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1., 1.]],

         [[1., 1., 1.],
          [1., 1.,

In [125]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [126]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [132]:
np.eye(1,2,3)

array([[0., 0.]])

In [133]:
np.logspace(2,10,20)

array([1.00000000e+02, 2.63665090e+02, 6.95192796e+02, 1.83298071e+03,
       4.83293024e+03, 1.27427499e+04, 3.35981829e+04, 8.85866790e+04,
       2.33572147e+05, 6.15848211e+05, 1.62377674e+06, 4.28133240e+06,
       1.12883789e+07, 2.97635144e+07, 7.84759970e+07, 2.06913808e+08,
       5.45559478e+08, 1.43844989e+09, 3.79269019e+09, 1.00000000e+10])

In [145]:
arr = np.random.randn(3, 4)

In [141]:
import pandas as pd

In [146]:
pd.DataFrame(arr)

0         1         2         3
0  0.617162 -0.878671 -0.479781  0.858367
1  1.274941  0.354949 -0.554944  0.901282
2 -0.580929 -0.373227  0.361383  1.397715

In [148]:
np.random.rand(3, 4)

array([[0.40454859, 0.52155001, 0.22561312, 0.42868883],
       [0.05649044, 0.2705725 , 0.02910312, 0.44623497],
       [0.84755872, 0.99906564, 0.47702928, 0.29205597]])

In [150]:
np.random.randint(1, 5, (5,6))

array([[4, 3, 1, 3, 1, 1],
       [1, 3, 4, 4, 3, 3],
       [1, 3, 1, 3, 1, 3],
       [3, 3, 2, 4, 3, 2],
       [2, 3, 3, 2, 3, 3]])

In [151]:
pd.DataFrame(np.random.randint(1, 5, (5,6)))

0  1  2  3  4  5
0  4  2  3  1  2  4
1  4  1  3  3  3  2
2  1  2  3  1  2  3
3  1  1  2  4  3  3
4  3  3  3  4  3  2

In [152]:
pd.DataFrame(np.random.randint(1, 5, (5,6))).to_csv("87_test_data.csv")

In [153]:
arr = np.random.rand(3,4)

In [154]:
arr

array([[0.77076935, 0.02764769, 0.12759916, 0.68535613],
       [0.97892663, 0.34066002, 0.2509492 , 0.63068397],
       [0.43501176, 0.8615914 , 0.17186879, 0.62038606]])

In [155]:
arr.reshape(2,6)

array([[0.77076935, 0.02764769, 0.12759916, 0.68535613, 0.97892663,
        0.34066002],
       [0.2509492 , 0.63068397, 0.43501176, 0.8615914 , 0.17186879,
        0.62038606]])

In [156]:
arr.reshape(4,3)

array([[0.77076935, 0.02764769, 0.12759916],
       [0.68535613, 0.97892663, 0.34066002],
       [0.2509492 , 0.63068397, 0.43501176],
       [0.8615914 , 0.17186879, 0.62038606]])

In [157]:
arr.reshape(8,-1)

ValueError: cannot reshape array of size 12 into shape (8,newaxis)

In [163]:
arr1 = arr.reshape(4,3)

In [164]:
arr1

array([[0.77076935, 0.02764769, 0.12759916],
       [0.68535613, 0.97892663, 0.34066002],
       [0.2509492 , 0.63068397, 0.43501176],
       [0.8615914 , 0.17186879, 0.62038606]])

In [165]:
arr1[1][1]

0.9789266271455517

In [169]:
arr1[2:3, 1]

array([0.63068397])

In [172]:
arr = np.random.randint(1, 100, (5, 5))

In [173]:
arr > 50

array([[ True,  True, False,  True, False],
       [ True,  True, False,  True,  True],
       [ True, False,  True, False, False],
       [False, False,  True, False,  True],
       [False, False, False, False, False]])

In [174]:
arr[arr>50]

array([71, 76, 89, 76, 97, 56, 72, 66, 75, 88, 90])

In [175]:
arr

array([[71, 76, 36, 89, 41],
       [76, 97, 40, 56, 72],
       [66, 34, 75, 46, 46],
       [46, 12, 88, 23, 90],
       [18, 26, 21, 41, 13]])

In [176]:
arr[2:3, (1,2)]

array([[34, 75]])

In [177]:
arr[2:3, [1,2]]

array([[34, 75]])

In [180]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [184]:
arr3 = arr1 + arr2

In [185]:
arr3

array([[2, 2, 2],
       [3, 3, 3],
       [2, 2, 2]])

In [186]:
arr1@arr2

array([[3, 4, 3],
       [5, 6, 5],
       [3, 4, 3]])

In [187]:
arr1 + 100

array([[101, 101, 101],
       [102, 101, 102],
       [101, 101, 101]])

In [188]:
arr4 = np.random.randint(1,5,[3,3])

In [189]:
arr4

array([[1, 2, 3],
       [4, 2, 4],
       [3, 2, 2]])

In [192]:
row = np.array([1,2,3])

In [193]:
arr4 + row

array([[2, 4, 6],
       [5, 4, 7],
       [4, 4, 5]])

In [198]:
col = np.array([[1,2,3]])

In [199]:
arr4 + col.T

array([[2, 3, 4],
       [6, 4, 6],
       [6, 5, 5]])

In [200]:
arr4

array([[1, 2, 3],
       [4, 2, 4],
       [3, 2, 2]])

In [201]:
np.sqrt(arr4)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 1.41421356, 2.        ],
       [1.73205081, 1.41421356, 1.41421356]])

In [202]:
np.exp(arr4)

array([[ 2.71828183,  7.3890561 , 20.08553692],
       [54.59815003,  7.3890561 , 54.59815003],
       [20.08553692,  7.3890561 ,  7.3890561 ]])